apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testhttpd
        tier: frontend
        track: stable
    spec:
      containers:
      - image: sbpcs59/httpd:latest
        name: httpd
        volumeMounts:
        - mountPath: /var/log/apache2
          name: httpd-claim0
      restartPolicy: Always
      volumes:
      - name: httpd-claim0
        persistentVolumeClaim:
          claimName: httpd-claim0
status: {}
