apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testhttpd
        tier: backend
        track: stable
    spec:
      containers:
      - image: sbpcs59/web:latest
        name: web
        resources: {}
      restartPolicy: Always
status: {}
